add support for setting topologyProfile in typedef files
oracle/weblogic-deploy-tooling pull request #1007
Opened 2021-11-16 09:31 UTC by httpants

Issue 1005
allows topologyProfile to be set in a typedef file.  eg

```
{
    "name": "OSB_COMPACT",
    "description": "OSB compact domain definitions",
    "topologyProfile": "Compact",
    "versions": {
        "12.2.1.4": "OSB_12CR2",
        "14.1":     "NOT_SUPPORTED"
    },
    "definitions": {
        "OSB_12CR2": {
            "baseTemplate": "Basic WebLogic Server Domain",
            "extensionTemplates": [
                "Oracle Service Bus",
                "Oracle Enterprise Scheduler Service Basic",
                "Oracle Enterprise Manager Plugin for ESS"
            ],
            "rcuSchemas": [ "WLS", "MDS", "IAU", "IAU_VIEWER", "IAU_APPEND", "OPSS", "UCSUMS", "SOAINFRA", "ESS" ]
        }
    }
}

```

2021-11-17 20:52 UTC, ddsharpe commented
Thank you for your interest in helping and improving WebLogic Deploy Tooling.  Please read the [contributing agreement](https://github.com/oracle/weblogic-deploy-tooling/blob/main/CONTRIBUTING.md) for this project.  You must have a signed agreement on file with Oracle and the PR must be signed by you before we can accept changes.

2021-11-17 20:53 UTC, ddsharpe requested changes
Needs OCA and signed commit.

2021-12-21 22:17 UTC, robertpatrick commented
@httpants Are you able to provide the requested documentation/update?  Please let us know if you need more time.  If we don't hear back from you, we will be forced to close this PR.

2022-01-13 16:59 UTC, robertpatrick commented
Closing PR due to lack of response from the contributor.

2022-01-13 16:59 UTC, closed without merging