return result in _process_roles_map to fix role edits
oracle/weblogic-deploy-tooling pull request #1133
Opened 2022-05-24 05:27 UTC by DSmithVA

looks like a previous cleanup commit removed the 'return result' line from _process_roles_map() - that removal prevents process_roles() from calling _update_xacml_role_mapper() with the role changes, so WLSRoles entries were not actually doing anything.

2022-05-24 19:01 UTC, robertpatrick approved these changes

2022-05-24 19:04 UTC, ddsharpe commented
This PR needs to be signed.

2022-05-24 19:07 UTC, robertpatrick commented
@DSmithVA In order for me to be able to merge your PR, please review the [CONTRIBUTING.md](https://github.com/oracle/weblogic-deploy-tooling/blob/main/CONTRIBUTING.md) file to sign the Contributor agreement and add a sign-off commit to your PR branch.

2022-05-24 19:08 UTC, ddsharpe requested changes
This request needs to be signed.  Please see https://github.com/oracle/weblogic-deploy-tooling/blob/main/CONTRIBUTING.md within this project for instructions on signing contributions.  Note, the signee needs to sign the Oracle Contributor's Agreement.  The OCA link is available within the CONTRIBUTING.md document.

2022-05-24 21:21 UTC, DSmithVA commented
i'm just getting errors from docusign, so if this one-liner can be done by someone else that'd be great

2022-05-25 00:36 UTC, robertpatrick commented
Replaced by #1134, as requested.

2022-05-25 00:36 UTC, closed without merging