fix server and server template alias definition for SSL password field
oracle/weblogic-deploy-tooling pull request #1161
Opened 2022-07-18 22:02 UTC by CarolynRountree

Fixes Jira 658
Fix SSL attribute OutboundPrivateKeyPassPhraseEncrypted  in both Server and ServerTemplate

2022-07-18 22:16 UTC, ddsharpe requested changes

2022-07-19 19:37 UTC, ddsharpe commented on core/src/main/resources/oracle/weblogic/deploy/aliases/category_modules/ServerTemplate.json
> +                "OutboundPrivateKeyPassPhrase":            [ {"version": "[12.1.2,]",         "wlst_mode": "both", "wlst_name": "OutboundPrivateKeyPassPhrase",            "wlst_path": "WP001", "defau
should be {"version": "[12.1.2,)"

2022-07-19 21:32 UTC, ddsharpe approved these changes

2022-07-19 21:33 UTC, rakillen approved these changes

2022-07-19 21:34 UTC, merged