Aliastest misc
oracle/weblogic-deploy-tooling pull request #1298
Opened 2022-11-28 23:00 UTC by CarolynRountree

alias definition changes for 14.1.1

2022-11-28 23:21 UTC, robertpatrick requested changes

2022-11-28 23:21 UTC, robertpatrick commented on core/src/main/resources/oracle/weblogic/deploy/aliases/category_modules/VirtualHost.json
> +                                          {"version": "[14.1.1,)",       "wlst_mode": "both",    "wlst_name": "NumberOfFilesLimited", "wlst_path": "WP001", "default_value": "${true:false}",
Clean up alignment at the end of this line.

2022-11-28 23:37 UTC, rakillen approved these changes

2022-11-29 09:36 UTC, robertpatrick approved these changes

2022-11-29 09:36 UTC, merged