Wkofilteruxmachine
oracle/weblogic-deploy-tooling pull request #750
Opened 2020-10-12 22:57 UTC by jshum2479

Missed deleting UnixMachine in wko filter

2020-10-13 18:29 UTC, rakillen requested changes
Not sure why simple-app.war was added with this commit. It looks like it should be generated by system-test/src/resources/build-archive.sh .

2020-10-13 23:27 UTC, jshum2479 commented on core/src/main/targetconfigs/wko/wko_operator_filter.py
> +        for delthis in [ 'NMProperties', 'VirtualTarget', 'Machine', 'UnixMachine']:
done

2020-10-14 18:50 UTC, rakillen approved these changes

2020-10-14 19:51 UTC, CarolynRountree approved these changes

2020-10-14 20:39 UTC, merged