Add restart changes
oracle/weblogic-deploy-tooling pull request #815
Opened 2020-12-21 23:01 UTC by jshum2479

rename the rollback_changes... to cancel_changes and rename rollback.file to non_dynamic_changes.file

2020-12-21 23:02 UTC, rakillen approved these changes

2020-12-21 23:38 UTC, CarolynRountree requested changes

2020-12-21 23:38 UTC, CarolynRountree commented on installer/src/main/bin/shared.cmd
> +      ECHO %SCRIPT_NAME% completed successfully but the domain changes have been canceled back because -cancel_changes_if_restart_required is specified  ^(exit code = %RETURN_CODE%^)
change canceled back to canceled

2020-12-21 23:38 UTC, CarolynRountree commented on installer/src/main/bin/shared.sh
> +      echo "$scriptName completed successfully but the domain changes have been canceled back because -cancel_changes_if_restart_required is specified (exit code = ${RETURN_CODE})"
change canceled back to canceled

2020-12-22 02:13 UTC, jshum2479 commented on installer/src/main/bin/shared.cmd
> +      ECHO %SCRIPT_NAME% completed successfully but the domain changes have been canceled back because -cancel_changes_if_restart_required is specified  ^(exit code = %RETURN_CODE%^)
changed

2020-12-22 15:13 UTC, CarolynRountree approved these changes

2020-12-22 17:39 UTC, ddsharpe approved these changes

2020-12-22 17:39 UTC, merged