Update rcudb
oracle/weblogic-deploy-tooling pull request #832
Opened 2021-02-03 01:03 UTC by jshum2479

2021-02-03 01:04 UTC, jshum2479 commented
Minor update to clarify the password fields

2021-02-03 15:05 UTC, rakillen approved these changes

2021-02-08 23:34 UTC, ddsharpe requested changes

2021-02-08 23:34 UTC, ddsharpe commented on site/rcuinfo.md
> +        not specify>
specify -> specified

2021-02-09 15:12 UTC, rakillen approved these changes

2021-02-09 19:58 UTC, jshum2479 commented on site/rcuinfo.md
> +        rcu_schema_password : <rcu schema password, will be prompted if not specify>
done

2021-02-09 19:58 UTC, jshum2479 commented on site/rcuinfo.md
> +        not specify>
done

2021-02-10 16:08 UTC, ddsharpe approved these changes

2021-02-10 21:24 UTC, merged