createDomain create LogFilter, XMLEntity Cache, and XML Registry earlier
oracle/weblogic-deploy-tooling pull request #872
Opened 2021-04-15 15:54 UTC by ddsharpe

Create LogFilter, XMLEntity Cache, and XML Registry earlier in the flow.  Server/Log depends on LogFilter.  Fixes #871

2021-04-15 16:00 UTC, rakillen approved these changes

2021-04-15 18:40 UTC, rakillen requested changes
This covers the "select template" create, but needs to be implemented for __extend_domain (older) create.

2021-04-15 18:55 UTC, CarolynRountree requested changes
update javadoc to reflect removal of location

2021-04-15 18:55 UTC, CarolynRountree commented on core/src/main/python/wlsdeploy/tool/create/domain_creator.py
>          :param location: current location
this javadoc is out of date.

2021-04-15 19:26 UTC, rakillen approved these changes

2021-04-16 19:25 UTC, CarolynRountree approved these changes

2021-04-19 14:43 UTC, merged