Fix issue 940
oracle/weblogic-deploy-tooling pull request #954
Opened 2021-07-28 07:42 UTC by belfo

Add support for & in id name

2021-07-28 16:14 UTC, rakillen approved these changes

2021-07-28 16:14 UTC, robertpatrick approved these changes

2021-07-28 18:06 UTC, ddsharpe commented
@belfo I see that you signed the commit, and all looks good.  Except, I do not see your name listed in the Oracle Contributors Agreement doc.  Have you or your company signed off on the OCA? See https://oca.opensource.oracle.com/

2021-07-28 18:06 UTC, ddsharpe requested changes
Needs OCA

2021-07-29 07:30 UTC, belfo commented
The OCA should be ok

2021-07-29 12:30 UTC, ddsharpe approved these changes

2021-07-29 12:30 UTC, merged