Wdt 579 add psu to version
oracle/weblogic-deploy-tooling pull request #992
Opened 2021-10-27 22:11 UTC by CarolynRountree

Add a PSU to the alias wls version number. Look for the psu in the oracle home location and add any psu found to the oracle version number.

2021-10-29 21:08 UTC, ddsharpe requested changes

2021-10-29 21:08 UTC, ddsharpe commented on core/src/main/resources/oracle/weblogic/deploy/aliases/category_modules/SecurityConfiguration.json
> +        "RemoteAnonymousRmiiiopEnabled":         [ {"version": "[12.2.1.4.0.210930,12.2.1.5)",   "wlst_mode": "both", "wlst_name": "RemoteAnonymous${Rmiiiop:RMIIIOP}Enabled", "wlst_path": "WP001", "v
what about the PSU for 12.2.1.3?

2021-10-29 21:08 UTC, ddsharpe commented on core/src/main/resources/oracle/weblogic/deploy/aliases/category_modules/SecurityConfiguration.json
> +        "RemoteAnonymousRmit3Enabled":           [ {"version": "[12.2.1.4.0.210930,12.2.1.5)",   "wlst_mode": "both", "wlst_name": "RemoteAnonymous${Rmit3:RMIT3}Enabled",  "wlst_path": "WP001", "valu
Shouldn't the version be 12.2.1.4.210930 instead of 12.2.1.4.0.210930?

2021-12-08 20:09 UTC, rakillen commented on core/src/main/resources/oracle/weblogic/deploy/messages/wlsdeploy_rb.properties
> +WLSDPLY-01050=Weblogic version for aliases is {0}
*WebLogic

2021-12-21 00:27 UTC, rakillen approved these changes

2021-12-22 18:07 UTC, ddsharpe requested changes

2021-12-22 18:07 UTC, ddsharpe commented on core/src/main/resources/oracle/weblogic/deploy/aliases/category_modules/SecurityConfiguration.json
> +        "RemoteAnonymousRmiiiopEnabled":         [ {"version": "[12.2.1.4.10930,12.2.1.5)",   "wlst_mode": "online", "wlst_name": "RemoteAnonymous${Rmiiiop:RMIIIOP}Enabled", "wlst_path": "WP001", "va
This is not the full list of changed attributes, nor does it include the versions for 12.2.1.3 and 12.2.1.5

2022-01-05 16:40 UTC, ddsharpe commented on core/src/main/java/oracle/weblogic/deploy/util/XPathUtil.java
> + * Copyright (c) 2021, Oracle Corporation and/or its affiliates.
Since this change did not make it into the main line by the end of the year, each of the copyrights needs to be changed to 2022.

2022-01-05 21:13 UTC, ddsharpe requested changes

2022-01-05 21:13 UTC, ddsharpe commented on core/src/main/resources/oracle/weblogic/deploy/aliases/category_modules/SecurityConfiguration.json
> +        "RemoteAnonymousRmiiiopEnabled":         [ {"version": "[12.2.1.4.10930,12.2.1.5)",   "wlst_mode": "online", "wlst_name": "RemoteAnonymous${Rmiiiop:RMIIIOP}Enabled", "wlst_path": "WP001", "va
Backports were done as part of bug 31498405.  These two attributes are included in these two PSUs (and all future PSUs in the same branch)
PSU 12.2.1.3.210329
PSU 12.2.1.4.210330

2022-01-06 00:52 UTC, robertpatrick approved these changes

2022-01-06 00:52 UTC, merged